>P1;1198
sequence:1198:1    :1:88  :1::::
-------QSCTQHQPYVVDDPCPIHFYSKWYIRVGARKSAPLIELCVDEAGSKSPIQYIDIGNYTVSCLP--FTINCQEPKLGSLVVR*
>P1;6W37
structure:6W37:6   :A:63  :A::Severe acute respiratory syndrome coronavirus 2:2.9:
-------QECVRGTTVLLKEPCSSGTYEG-----------------------NSPFHPLADNKFALTCFSTQFAFACPDGVKHVYQLR*

